# -*- coding: utf-8 -*-
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os
import alabaster
import mock

# All imported modules containing C components must be mocked (added to the
# MOCK_MODULES list below)

MOCK_MODULES = ['numpy', 'scipy', 'matplotlib', 'matplotlib.pyplot',
                'sklearn.grid_search', 'sklearn.externals', 'plotly',
                'plotly.graph_objs', 'matplotlib.gridspec', 'scikit-learn',
                'pandas', 'IPython.display', 'plotly.plotly', 'plotly', 'plotly.tools',
                'libpng', 'freetype', 'IPython', 'past', 'past.builtins', 'builtins', 'past.utils']

for mod_name in MOCK_MODULES:
    sys.modules[mod_name] = mock.Mock()
sys.path.insert(0, os.path.abspath('../transcriptic'))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
needs_sphinx = '1.2'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon'
]

# Napoleon settings
napoleon_google_docstring = False
napoleon_numpy_docstring = True
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = True
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True

autodoc_member_order = 'bysource'

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'transcriptic'
copyright = u'2015, Max Hodak, Tali Herzka, Jeremy Apthorp, Yang Choo, Peter Lee'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '2.0.4'
# The full version, including alpha/beta/rc tags.
release = '2.0.4'

# The reST default role (used for this markup: `text`) to use for all
# documents.
#default_role = None

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
add_module_names = True

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
#keep_warnings = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'default'

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
#html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
#html_domain_indices = True

# If false, no index is generated.
html_use_index = True

# If true, the index is split into individual pages for each letter.
html_split_index = False

# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
html_show_copyright = True

# Output file base name for HTML help builder.
htmlhelp_basename = 'transcripticdoc'

# on_rtd is whether we are on readthedocs.org
on_rtd = os.environ.get('READTHEDOCS', None) == 'True'

if not on_rtd or on_rtd:
    html_theme_path = [alabaster.get_path()]
    html_style = '/alabaster.css'
    html_theme = 'alabaster'
    html_sidebars = {
        '**': [
            'about.html',
            'navigation.html',
            'relations.html',
            'searchbox.html',
            'donate.html',
        ]
    }
    html_theme_options = {
      'logo_text_align': 'center',
      'description': "A command-line interface and Python client library for interacting with Transcriptic's API.",
      'github_user': 'transcriptic',
      'github_repo': 'transcriptic',
      'github_button': True,
      'github_count': False,
      'github_type': 'follow',
      'extra_nav_links': {
          "Transcriptic Homepage": "http://transcriptic.com",
          "Autoprotocol.org": "http://autoprotocol.org",
          "Autoprotocol-Python": "http://autoprotocol-python.readthedocs.org"
      },
      'font_family': "Source Sans Pro",
      'head_font_family': "Source Sans Pro",
      'show_powered_by': False,
      'sidebar_width': "300px"
    }
